// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAYErvDbBujHnjW808sNRiGR-UAZrHipio',
//     appId: '1:6547935584:web:5e126f66709f858dbb4e05',
//     messagingSenderId: '6547935584',
//     projectId: 'gohealthy-a644d',
//     authDomain: 'gohealthy-a644d.firebaseapp.com',
//     storageBucket: 'gohealthy-a644d.appspot.com',
//     measurementId: 'G-0BYL4066PM',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCSwi7RGjepxxYznP1lHhUeF271NJEzoDk',
//     appId: '1:6547935584:android:10534809c976376abb4e05',
//     messagingSenderId: '6547935584',
//     projectId: 'gohealthy-a644d',
//     storageBucket: 'gohealthy-a644d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAO9SwV0k07GWDMEvhkBHPAqchIY5IXMcM',
//     appId: '1:6547935584:ios:694366e737459e03bb4e05',
//     messagingSenderId: '6547935584',
//     projectId: 'gohealthy-a644d',
//     storageBucket: 'gohealthy-a644d.appspot.com',
//     iosBundleId: 'com.gohealthy.cc',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAO9SwV0k07GWDMEvhkBHPAqchIY5IXMcM',
//     appId: '1:6547935584:ios:7ed563da43f20a89bb4e05',
//     messagingSenderId: '6547935584',
//     projectId: 'gohealthy-a644d',
//     storageBucket: 'gohealthy-a644d.appspot.com',
//     iosBundleId: 'com.example.financialtools',
//   );
// }
